version: '3.8'


services:

  db:
    image: postgres
    volumes:
      - ./db_api/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PORT__DB}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  dbapi:
    build:
      context: ./db_api
    ports:
      - ${PORT__DB_API}:80
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


  voteapi:
    build:
      context: ./vote_api
    volumes:
      - ./vote_api:/app
    ports:
      - ${PORT__VOTE_API}:80
    environment:
      DB_HOST: dbapi


  resultsapi:
    build:
      context: ./results_api
    volumes:
      - ./results_api:/app
    ports:
      - ${PORT__RESULTS_API}:80
    environment:
      DB_HOST: dbapi
