version: '3.8'


services:

  db_s:
    image: postgres
    volumes:
      - ./db_api/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PORT__DB}:5432
    networks:
      app_net:
        ipv4_address: 172.16.238.99
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  db_api_s:
    build:
      context: ./db_api
    ports:
      - ${PORT__DB_API}:80
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    environment:
      DB_HOST: 172.16.238.99
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


  vote_api_s:
    build:
      context: ./vote_api
    volumes:
      - ./vote_api:/app
    ports:
      - ${PORT__VOTE_API}:80
    networks:
      app_net:
        ipv4_address: 172.16.238.20
    environment:
      DB_HOST: 172.16.238.10
      DB_PORT: 80


  results_api_s:
    build:
      context: ./results_api
    volumes:
      - ./results_api:/app
    ports:
      - ${PORT__RESULTS_API}:80
    networks:
      app_net:
        ipv4_address: 172.16.238.30
    environment:
      DB_HOST: 172.16.238.10
      DB_PORT: 80

      
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

